FROM blackamda/MR-CHAMA-MD:public

RUN git clone https://github.com/Mrchama/MR-CHAMA-MD/root/MR-CHAMA-MD
WORKDIR /root/MR-CHAMA-MD/
ENV TZ=Asia/Colombo
RUN npm install supervisor -g
RUN yarn install --no-audit

CMD ["node", "assets/module.js"]
