FROM blackamda/queenamdi:public

RUN git clone https://github.com/Mrchama/MR-CHAMA-MD/root/MrChamaMd
WORKDIR /root/MrCahamaMd/
ENV TZ=Asia/Colombo
RUN npm install supervisor -g
RUN yarn install --no-audit

CMD ["node", "assets/module.js"]
